# Generated by Django 3.2.9 on 2023-02-07 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('role', models.CharField(choices=[('student', 'student'), ('professor', 'PROFESSOR')], max_length=20)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('street_number', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
                ('post_number', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'fh_user',
            },
        ),
    ]
